#ifndef HAVE_TL_PARSER_H
#define HAVE_TL_PARSER_H

#include <glib.h>

typedef struct _TLParserSignalData
{
    int id;
    gchar *name;
    gboolean endian;
    guint firstbyte;
    guint firstbit;
    guint bitlength;
    gdouble unit;
    int offset;
    guint listindex;
    gchar *listparent;
    int source;
}TLParserSignalData;

#define TL_PARSER_VEHICLE_STATE "VCU01_PTReady"
#define TL_PARSER_BATTERY_STATE "BMS01_BatState"
#define TL_PARSER_RUNNING_MODE "BMS01_PTMode"
#define TL_PARSER_VEHICLE_SPEED "VCU08_VehicleSpeed"
#define TL_PARSER_TOTAL_MILEAGE "DPU01_ODO"
#define TL_PARSER_TOTAL_VOLTAGE "BMS01_actVoltage"
#define TL_PARSER_TOTAL_CURRENT "BMS01_actCurrent"
#define TL_PARSER_SOC_STATE "BMS01_actSOC"
#define TL_PARSER_DC2DC_STATE "VCU09_StOpMode"
#define TL_PARSER_GEAR_SHIFT_STATE "VCU01_StGear"
#define TL_PARSER_INSULATION_RESISTANCE "BMS02_IsoResistance"
#define TL_PARSER_ACCELERATOR_LEVEL "VCU03_GasNrm"
#define TL_PARSER_BRAKE_LEVEL "VCU01_bBrk"

#define TL_PARSER_DRIVE_MOTOR_NUMBER "VCU08_EMNumber"
#define TL_PARSER_DRIVE_MOTOR_INDEX "VCU08_EMIndex"
#define TL_PARSER_DRIVE_MOTOR_STATE "VCU01_EMMode"
#define TL_PARSER_DRIVE_MOTOR_CONTROLLER_TEMPERATURE "VCU03_MCUTemp"
#define TL_PARSER_DRIVE_MOTOR_SPIN_SPEED "VCU01_EMSpeed"
#define TL_PARSER_DRIVE_MOTOR_TORQUE "VCU02_EMTrq"
#define TL_PARSER_DRIVE_MOTOR_TEMPERATURE "VCU03_EMTemp"
#define TL_PARSER_DRIVE_MOTOR_CONTROLLER_VOLTAGE "VCU05_CapVoltage"
#define TL_PARSER_DRIVE_MOTOR_CONTROLLER_CURRENT "VCU05_PTCurrent"

#define TL_PARSER_BATTERY_SUBSYSTEM_MAX_VOLTAGE_ID "BMS08_BatIndex"
#define TL_PARSER_BATTERY_CELL_MAX_VOLTAGE_ID "BMS05_MaxVoltCellID"
#define TL_PARSER_BATTERY_CELL_MAX_VOLTAGE "BMS05_MaxCellVolt"
#define TL_PARSER_BATTERY_SUBSYSTEM_MIN_VOLTAGE_ID "BMS08_BatIndex"
#define TL_PARSER_BATTERY_CELL_MIN_VOLTAGE_ID "BMS05_MinVoltCellID"
#define TL_PARSER_BATTERY_CELL_MIN_VOLTAGE "BMS05_MinCellVolt"
#define TL_PARSER_BATTERY_SUBSYSTEM_MAX_TEMPERATURE_ID "BMS08_BatIndex"
#define TL_PARSER_BATTERY_CELL_MAX_TEMPERATURE_ID "BMS06_MaxTempCellID"
#define TL_PARSER_BATTERY_CELL_MAX_TEMPERATURE "BMS06_MaxTemp"
#define TL_PARSER_BATTERY_SUBSYSTEM_MIN_TEMPERATURE_ID "BMS08_BatIndex"
#define TL_PARSER_BATTERY_CELL_MIN_TEMPERATURE_ID "BMS06_MinTempCellID"
#define TL_PARSER_BATTERY_CELL_MIN_TEMPERATURE "BMS06_MinTemp"

#define TL_PARSER_VEHICLE_FAULT_LEVEL "VCU01_VehicleFaultLevel"
#define TL_PARSER_ALARM_TEMPERATURE_DIFF "BMS02_FaultTempDiff"
#define TL_PARSER_ALARM_BATTERY_OVERHEAT "BMS02_FaultOverTemp"
#define TL_PARSER_ALARM_BATTERY_OVERVOLTAGE "BMS02_FaultOverVolt"
#define TL_PARSER_ALARM_BATTERY_UNDERVOLTAGE "BMS02_FaultUnderVolt"
#define TL_PARSER_ALARM_SOC_LOW "BMS02_FaultSOCLow"
#define TL_PARSER_ALARM_BATTERY_CELL_OVERVOLTAGE "BMS02_FaultCellOverVolt"
#define TL_PARSER_ALARM_BATTERY_CELL_UNDERVOLTAGE "BMS02_FaultCellUnderVolt"
#define TL_PARSER_ALARM_SOC_HIGH "BMS02_FaultSOCHigh"
#define TL_PARSER_ALARM_SOC_JUMP "VCU01_FaultSOCJump"
#define TL_PARSER_ALARM_BATTERY_MISMATCH "BMS02_FaultMismatch"
#define TL_PARSER_ALARM_BATTERY_CONSIST "BMS02_FaultConsist"
#define TL_PARSER_ALARM_BAD_INSULATION "BMS02_FaultIsoLow"
#define TL_PARSER_ALARM_BRAKE_OVERHEAT "VCU09_bOverTemp"
#define TL_PARSER_ALARM_EVP "VCU01_FaultEVP"
#define TL_PARSER_ALARM_DC2DC "VCU01_FaultDCDC"
#define TL_PARSER_ALARM_DRIVE_MOTOR_CONTROLLER_TEMPERATURE "VCU01_bVPUOverTemp"
#define TL_PARSER_ALARM_EMERGENCY_OFF_PILOT "BMS01_EmgcyOff_Pilot"
#define TL_PARSER_ALARM_DRIVE_MOTOR_TEMPERATURE "VCU01_bEMOverTemp"
#define TL_PARSER_ALARM_SOC_OVERCHARGE "BMS02_FaultSOCHigh"

#define TL_PARSER_BATTERY_NUMBER "BMS08_BatNumber"

gboolean tl_parser_init();
void tl_parser_uninit();
gboolean tl_parser_load_parse_file(const gchar *file);
gboolean tl_parser_parse_can_data(const gchar *device,
    int can_id, const guint8 *data, gsize len);
const gchar *tl_parser_battery_code_get(guint8 *single_bat_code_len,
    guint *bat_code_total_len);

#endif
